name: PHPCS Code Quality

on:
  pull_request:
    paths:
      - 'src/**/*.php'  # Only run when PHP files in src/ changes

jobs:
  phpcs:
    name: Run PHPCS on PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run PHPCS (fail on errors only)
        run: |
          vendor/bin/phpcs --standard=phpcs.xml --severity=0 --error-severity=1 --warning-severity=0